

[build]

command = "netlify-lambda build src"
commandOrigin = "config"
publish = "/build/src"
publishOrigin = "config"
functionsDirectory = "/build/handler"
directory = "netlify"
functions = "handler"

[[redirects]]
from = "/"
to = "/.netlify/handler"
status = 200
redirectsOrigin = "config"