

[build]

# base = "src"
command = "npm run build src"
commandOrigin = "config"
publish = "src/"
publishOrigin = "config"
functionsDirectory = "/build/handler"
directory = "netlify"
functions = "handler"

[[redirects]]
from = "/"
to = "/.netlify/handler"
status = 200
redirectsOrigin = "config"