

[build]

command = "netlify-lambda build src"
commandOrigin = "config"
publish = "/opt/build/repo/build"
publishOrigin = "config"
functionsDirectory = "/opt/build/repo/handler"
directory = "netlify"
functions = "handler"

[[redirects]]
from = "/"
to = "/.netlify/handler"
status = 200
redirectsOrigin = "config"